server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location /chatbot/static/ {
        try_files $uri $uri/ /chatbot/static/index.html;
    }

    location /chatbot/ {
        try_files $uri $uri/ /chatbot/static/index.html;
    }

    location / {
        return 302 /chatbot/static/;
    }
}
